version: '3'
services:
  node-app:
    build:
      context: ../../  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - green

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always


networks:
  green:
    external:
      name: green
