version: '3'
services:
  node-app:
    build:
      context: ../../  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - green

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-shell:
    image: mongo:latest
    command: ["mongo"]
    depends_on:
      - mongo

networks:
  green:
    external:
      name: green
