version: '3'
services:
  redis:
    image: redis:7.0.4
    container_name : redis
    hostname: redis
    ports:
      - "6388:6388"
    volumes:
    - ./solr-data:/var/solr/data 
    - ./solr-config:/opt/solr/server/solr/configsets/myconfig 
    restart: always
    networks:
      - green

networks:
  green:
    external:
      name: green
